// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PCSR.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct PBCertificateSigningRequest: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.
    
    var version: String = String()
    
    var subjectName: String = String()
    
    var subjectID: Data = Data()
    
    var subjectDomain: String = String()
    
    var name: String = String()
    
    var id: Data = Data()
    
    var domain: String = String()
    
    var publicKey: Data = Data()
    
    var `extension`: [PBElement] = []
    
    var unknownFields = SwiftProtobuf.UnknownStorage()
    
    init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension PBCertificateSigningRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "CertificateSigningRequest"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "version"),
        2: .standard(proto: "subject_name"),
        3: .standard(proto: "subject_ID"),
        4: .standard(proto: "subject_domain"),
        5: .same(proto: "name"),
        6: .same(proto: "id"),
        7: .same(proto: "domain"),
        8: .standard(proto: "public_key"),
        9: .same(proto: "extension"),
    ]
    
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try { try decoder.decodeSingularStringField(value: &self.version) }()
            case 2: try { try decoder.decodeSingularStringField(value: &self.subjectName) }()
            case 3: try { try decoder.decodeSingularBytesField(value: &self.subjectID) }()
            case 4: try { try decoder.decodeSingularStringField(value: &self.subjectDomain) }()
            case 5: try { try decoder.decodeSingularStringField(value: &self.name) }()
            case 6: try { try decoder.decodeSingularBytesField(value: &self.id) }()
            case 7: try { try decoder.decodeSingularStringField(value: &self.domain) }()
            case 8: try { try decoder.decodeSingularBytesField(value: &self.publicKey) }()
            case 9: try { try decoder.decodeRepeatedMessageField(value: &self.`extension`) }()
            default: break
            }
        }
    }
    
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !self.version.isEmpty {
            try visitor.visitSingularStringField(value: self.version, fieldNumber: 1)
        }
        if !self.subjectName.isEmpty {
            try visitor.visitSingularStringField(value: self.subjectName, fieldNumber: 2)
        }
        if !self.subjectID.isEmpty {
            try visitor.visitSingularBytesField(value: self.subjectID, fieldNumber: 3)
        }
        if !self.subjectDomain.isEmpty {
            try visitor.visitSingularStringField(value: self.subjectDomain, fieldNumber: 4)
        }
        if !self.name.isEmpty {
            try visitor.visitSingularStringField(value: self.name, fieldNumber: 5)
        }
        if !self.id.isEmpty {
            try visitor.visitSingularBytesField(value: self.id, fieldNumber: 6)
        }
        if !self.domain.isEmpty {
            try visitor.visitSingularStringField(value: self.domain, fieldNumber: 7)
        }
        if !self.publicKey.isEmpty {
            try visitor.visitSingularBytesField(value: self.publicKey, fieldNumber: 8)
        }
        if !self.`extension`.isEmpty {
            try visitor.visitRepeatedMessageField(value: self.`extension`, fieldNumber: 9)
        }
        try unknownFields.traverse(visitor: &visitor)
    }
    
    static func ==(lhs: PBCertificateSigningRequest, rhs: PBCertificateSigningRequest) -> Bool {
        if lhs.version != rhs.version {return false}
        if lhs.subjectName != rhs.subjectName {return false}
        if lhs.subjectID != rhs.subjectID {return false}
        if lhs.subjectDomain != rhs.subjectDomain {return false}
        if lhs.name != rhs.name {return false}
        if lhs.id != rhs.id {return false}
        if lhs.domain != rhs.domain {return false}
        if lhs.publicKey != rhs.publicKey {return false}
        if lhs.`extension` != rhs.`extension` {return false}
        if lhs.unknownFields != rhs.unknownFields {return false}
        return true
    }
}

